# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_designer_files/export_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chooseFileButton = QtWidgets.QPushButton(Form)
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.verticalLayout.addWidget(self.chooseFileButton)
        self.exportButton = QtWidgets.QPushButton(Form)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.errorField = QtWidgets.QLabel(Form)
        self.errorField.setText("")
        self.errorField.setObjectName("errorField")
        self.verticalLayout_2.addWidget(self.errorField)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Экспорт данных"))
        self.chooseFileButton.setText(_translate("Form", "Выбрать местоположение файла"))
        self.exportButton.setText(_translate("Form", "Экспортировать"))
