# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_designer_files/statistics.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.speedField = QtWidgets.QDoubleSpinBox(Form)
        self.speedField.setReadOnly(True)
        self.speedField.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.speedField.setMaximum(10000.0)
        self.speedField.setObjectName("speedField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speedField)
        self.accuracyField = QtWidgets.QDoubleSpinBox(Form)
        self.accuracyField.setReadOnly(True)
        self.accuracyField.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.accuracyField.setMaximum(100.0)
        self.accuracyField.setObjectName("accuracyField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.accuracyField)
        self.errorCntField = QtWidgets.QSpinBox(Form)
        self.errorCntField.setReadOnly(True)
        self.errorCntField.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.errorCntField.setMaximum(1000)
        self.errorCntField.setObjectName("errorCntField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.errorCntField)
        self.symbolTypedField = QtWidgets.QSpinBox(Form)
        self.symbolTypedField.setReadOnly(True)
        self.symbolTypedField.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.symbolTypedField.setMaximum(1000)
        self.symbolTypedField.setObjectName("symbolTypedField")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.symbolTypedField)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Скорость"))
        self.label_2.setText(_translate("Form", "Точность"))
        self.label_3.setText(_translate("Form", "Ошибок совершено"))
        self.label_4.setText(_translate("Form", "Символов напечатано"))
