# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_designer_files/test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 506)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.speed = QtWidgets.QDoubleSpinBox(Form)
        self.speed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.speed.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.speed.setReadOnly(True)
        self.speed.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.speed.setMaximum(9999.0)
        self.speed.setObjectName("speed")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speed)
        self.accuracy = QtWidgets.QDoubleSpinBox(Form)
        self.accuracy.setReadOnly(True)
        self.accuracy.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.accuracy.setMaximum(100.0)
        self.accuracy.setProperty("value", 100.0)
        self.accuracy.setObjectName("accuracy")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.accuracy)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)
        self.textField = QtWidgets.QTextBrowser(Form)
        self.textField.setObjectName("textField")
        self.gridLayout.addWidget(self.textField, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Скорость"))
        self.label_2.setText(_translate("Form", "Точность"))
        self.speed.setSuffix(_translate("Form", " зн/мин"))
        self.accuracy.setSuffix(_translate("Form", "%"))
        self.textField.setHtml(_translate("Form",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                          "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"lipsum\"></a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae sapien augue. Etiam vestibulum a libero et suscipit. Pellentesque ante elit, placerat ut nisl ac, hendrerit bibendum leo. Nunc a ipsum vel lectus bibendum porta. In eget laoreet mi. Nulla facilisi. Ut cursus nulla eu nulla sollicitudin dignissim. Morbi pretium commodo scelerisque. </p>\n"
                                          "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nullam sollicitudin eget augue et auctor. Quisque tortor nisl, cursus non pretium ac, pulvinar non lorem. Integer a vestibulum massa, in semper neque. Nunc nisi augue, luctus at elementum auctor, aliquam nec arcu. Duis bibendum eleifend ultricies. Sed id dolor dictum, fermentum urna ac, aliquet nulla. Suspendisse eget nulla mi. Fusce hendrerit tellus in sodales malesuada. </p>\n"
                                          "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nulla finibus vitae enim porttitor porttitor. Donec sagittis fringilla tortor vehicula iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam nec malesuada dolor. Etiam nec fringilla turpis, et scelerisque lorem. Sed eget nunc ac nunc pellentesque pretium. Aliquam molestie massa nec tortor sollicitudin elementum. Sed vitae rhoncus felis. Phasellus ut enim fermentum, congue diam a, luctus nisi. Donec finibus, neque a vehicula sodales, neque augue vestibulum ipsum, ut feugiat nunc lorem sit amet elit. Duis finibus condimentum urna, ac gravida tortor vulputate non. Vivamus feugiat nisi in. </p></body></html>"))
